title: Example
description: Example
lsi: false
safe: true
incremental: false
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
gist:
  noscript: false
github:
  zip_url: https://github.com/r00k13d3v/todo-app-backend/archive/refs/heads/main.zip
  another_url: https://rookiedev.net
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
